---
title: "Program"
---

***
### 🏨 Venue Information
The main symposium is held at the **QT Hotel Perth** at 133 Murray Street in the heart of Perth CBD. Most sessions take place inside the **Murray Room**.

<!-- 🏨 **Venue Note:** The main symposium is held at the **QT Hotel Perth** at 133 Murray Street in the heart of Perth CBD. Most sessions take place inside the **Murray Room**. -->
***

## Schedule at a Glance

| Time Block | Mon 9/11 (Day 0) | Tue 10/11 (Day 1) | Wed 11/11 (Day 2) | Thu 12/11 (Day 3) |
|:---|:---|:---|:---|:---|
| **08:30 - 09:00** | | **Opening by GRDC** | | |
| **09:00 - 10:30** | **Workshop (UQ)** | **Talks: CU** | **Talks: UQ** | **Talks: AU** |
| **10:30 - 11:00** | _Workshop cont._| ☕ Morning Tea | ☕ Morning Tea | ☕ Morning Tea |
| **11:00 - 13:00** | _Workshop cont._ | **Workshops 1a / 1b** | **Workshops 2a / 2b** | **Workshop 3** |
| **13:00 - 14:00** | _Workshop cont._ | 🥪 Lunch | 🥪 Lunch | 🏆 **Closing & Awards** |
| **14:00 - 15:30** | _Workshop cont._ | **Industry/Government/Growers** | **Talks: ANU/Guests** | 🥡 Take-away Lunch |
| **15:30 - 16:00** | _Workshop cont._ | ☕ Afternoon Tea | ☕ Afternoon Tea | |
| **16:00 - 17:30** | _Free time_ | 📊 **Poster Session** | 👭 **HDR Networking Session** | |
| **17:30 - 18:30** | _Free time_ | 📊 **Poster Session** | _Free time_ | |
| **18:30 - 20:30** | 🥂 **Welcome Mixer** | | 🍽️ **Symposium Dinner** | |

## Daily Schedule

::: {.panel-tabset}

### Day 0: Monday 9/11

| Time | Session | Location |
|:---|:---|:---|
| **9:00 - 16:00** | **Workshop (UQ)** <br> *TBC* | Murray Room |
| **16:00 - 18:30** | *Free time* | |
| **18:30 - 20:30** | 🥂 **Welcome Mixer** <br> *Icebreaker and networking social evening.* | Rooftop Bar |

### Day 1: Tuesday 10/11

| Time | Session | Location |
|:---|:---|:---|
| **08:30 - 09:00** | **Opening by GRDC** | Murray Room |
| **09:00 - 10:30** | **Talks: CU** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 1a** <br> *Stream A session.* | Murray Room |
| | **Workshop 1b** <br> *Stream B parallel session.* | *TBA* |
| **13:00 - 14:00** | 🥪 Lunch | Murray Room |
| **14:00 - 15:30** | **Industry/Government/Growers** | Murray Room |
| **15:30 - 16:00** | ☕ Afternoon Tea | Murray Room |
| **16:00 - 18:30** | 📊 **Poster Session** | Murray Room |

### Day 2: Wednesday 11/11

| Time | Session | Location |
|:---|:---|:---|
| **09:00 - 10:30** | **Talks: UQ** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 2a** <br> *Stream A session.* | Murray Room |
| | **Workshop 2b** <br> *Stream B parallel session.* | *TBA* |
| **13:00 - 14:00** | 🥪 Lunch | Murray Room |
| **14:00 - 15:30** | **Talks: ANU / Guests** | Murray Room |
| **15:30 - 16:00** | ☕ Afternoon Tea | Murray Room |
| **16:00 - 17:30** | 👭 **HDR Networking Session** | Murray Room |
| **17:30 - 18:30** | *Free time* | |
| **18:30 - 20:30** | 🍽️ **Symposium Dinner** | *TBA (Offsite Venue)* |

### Day 3: Thursday 12/11

| Time | Session | Location |
|:---|:---|:---|
| **09:00 - 10:30** | **Talks: AU** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 3**  <br> *What will AAGI 2.0 look like?*  | Murray Room |
| **13:00 - 14:00** | 🏆 **Closing & AAGI Awards** | Murray Room |
| **14:00+** | 🥡 Take-away Lunch & Departure | Murray Room |

:::

